### PR TITLE
Update database.py

### PR DESCRIPTION
**Pull request by Operator-F0x**
small structural improvements added prints of the connection and closing

### CODE REVIEW

**Review by KaSaNaa — APPROVED** [review]
Thank you for your contribution! I appreciate the improvements. I'm still working on this, and it is not yet finalized.

**Comment by Operator-F0x** [comment]
I noticed it, for anything just ask, I was interested in your project because I was creating it too for my study project

**Comment by KaSaNaa** [comment]
> I noticed it, for anything just ask, I was interested in your project because I was creating it too for my study project

no prob. make any creative changes as you like, and PR here. 
currently SNMP v1, 2 and 3 based discovery is in progress.

**Comment by Operator-F0x** [comment]
> > I noticed it, for anything just ask, I was interested in your project because I was creating it too for my study project
> 
> no prob. make any creative changes as you like, and PR here. currently SNMP v1, 2 and 3 based discovery is in progress.

perfect and thank you very much, with your permission in the fork I created I want to do a complete refactoring, then if you like it take a look

**Comment by KaSaNaa** [comment]
sure. Please PR here if you got a minute.

**Comment by Operator-F0x** [comment]
what do you mean by PR? do you mean push request? obviously how did i finish if that's what you mean, at the moment i still have to start because i'm creating a virtual python environment so as to stabilize all the dependencies and the python version

**Pull request merged**
